disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "ğŸ‡¬ğŸ‡·ã€Greek in Japanã€‘ğŸ‡¯ğŸ‡µ"
logo = "/img/logo.png"

[params]
displayName = "EN ğŸ‡¬ğŸ‡§"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "The untouristic sites of Japan"
