disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 2
title = "JA ğŸ‡¬ğŸ‡·ã€Greek in Japanã€‘ğŸ‡¯ğŸ‡µ"

[params]
displayName = "JA ğŸ‡¯ğŸ‡µ"
isoCode = "ja"
rtl = false
dateFormat = "2006 January 02"
description = "The untouristic sites of Japan"
