disabled = false
languageCode = "gr"
languageName = "Greek"
weight = 2
title = "ğŸ‡¬ğŸ‡·ã€Greek in Japanã€‘ğŸ‡¯ğŸ‡µ"

[params]
displayName = "GR ğŸ‡¬ğŸ‡·"
isoCode = "gr"
rtl = false
dateFormat = "02 January 2006"
description = "The untouristic sites of Japan"
